services:
  proxy:
    image: reverse-proxy
    build:
      context: proxy
    volumes:
      - ./proxy/example-config.yaml:/etc/proxy/config.yaml
    ports:
      - 5000:5000
    networks:
      - proxy-network

  service:
    image: summation-service
    build:
      context: sample/service
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "10.0.0.0/16"
